### ISSUE TITLE
How can I get the record number where I am?

### ISSUE THREAD

**Issue by bich30** [albfernandez/javadbf#63]
When I am reading a database,
How can I get the record number where I am?
Thank you

**Comment by albfernandez** [comment]
Currently it's not possible with javadbf itself, you must do it on your own: ie using a counter which increments on every nextRecord() call

**Comment by bich30** [comment]
Thank you.
That is what I am doing but the accountant counts the undeleted records that I have read but when I later place myself in a certain register using skipRecords it leaves me in another position since the deleted records are counted.  It is right ?
For me it is not a problem, but it is to know how it works.
Thank you!!!

**Comment by albfernandez** [comment]
Maybe the logic of skipRecords is wrong. It should ignore the deleted records (or not, if you use showDeletedRecord = true).

I think 9e4120fdaf7f7664f67c7fb550e551ec033a8e79 solves the problem

**Comment by bich30** [comment]
Muchas gracias!!!
Es una gran libreria!!

**Comment by mwithake** [comment]
I have the same requirement, to know which record I currently have. I need to read a log file of a machine and work with skipRecords() to avoid having to re-read all records. DBFReader has the field “internalRecord”, why was this not made accessible e.g. with getCurrentRecord()? 

Occasionally I get the stacktrace listed below. This probably happens when the machine is writing at the same time as I am reading. I could work around the error by setting the number of records before reading and only reading until then and thus not getting any records added in the meantime. “internalRecord” would help here.

com.linuxense.javadbf.DBFException
	at com.linuxense.javadbf.DBFReader.nextRecord(DBFReader.java:391)
	at com.linuxense.javadbf.DBFReader.nextRow(DBFReader.java:405)
	at betonwaren.app.mischungsprotokoll.SteinformmaschineDatenAbholenNeu.datenAbholen(SteinformmaschineDatenAbholenNeu.java:124)
	at core.app.cron.Cron.lambda$16(Cron.java:244)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.linuxense.javadbf.DBFUtils.readLittleEndianInt(DBFUtils.java:100)
	at com.linuxense.javadbf.DBFReader.getFieldValue(DBFReader.java:460)
	at com.linuxense.javadbf.DBFReader.nextRecord(DBFReader.java:346)
